import type { ThinUiThemeDefinition } from "../contracts/types";

export const thinUiC64Theme: ThinUiThemeDefinition = {
  id: "thinui-c64",
  label: "Thinui C64",
  family: "c64",
  surface: "thinui",
  description: "Commodore-inspired thinui skin adapted for low-resource local uDOS panels.",
  upstream: {
    name: "c64css3",
    repo: "https://github.com/RoelN/c64css3",
    strategy: "fork",
  },
  defaultFontId: "petme-default",
  defaultLoaderId: "c64-boot-seq",
  palettes: {
    normal: {
      background: "#40318d",
      foreground: "#a7a7ff",
      accent: "#8cf0ff",
      accentMuted: "#6fb5ff",
      border: "#a7a7ff",
      danger: "#ff8ca1",
      warning: "#ffd37a",
      success: "#90ff90",
    },
    recovery: {
      background: "#1a1a40",
      foreground: "#d8d8ff",
      accent: "#a7a7ff",
      accentMuted: "#8c8cff",
      border: "#d8d8ff",
      danger: "#ff8ca1",
      warning: "#ffd37a",
      success: "#90ff90",
    },
  },
  panel: {
    borderStyle: "double",
    radius: "none",
    shadow: false,
    padding: "normal",
  },
  cssClasses: {
    app: "theme-c64 thinui-app",
    panel: "thinui-panel thinui-panel-c64",
    title: "thinui-title thinui-title-c64",
    subtitle: "thinui-subtitle thinui-subtitle-c64",
    status: {
      idle: "status-idle-c64",
      running: "status-running-c64",
      warning: "status-warning-c64",
      error: "status-error-c64",
      complete: "status-complete-c64",
    },
    actionPrimary: "btn-c64-primary",
    actionSecondary: "btn-c64-secondary",
    actionDanger: "btn-c64-danger",
  },
  capabilities: {
    animation: true,
    gamepadHints: true,
    lowResourceSafe: true,
    fullscreenRecommended: true,
  },
};
